config/routes.rb
Csv401k::Application.routes.draw do
  resources :employees

end

app/models/employee.rb
class Employee
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  validates_presence_of :last_name, :first_name

  attr_accessor :last_name, :first_name, :middle_initial, :ssn, :birth_date, :hire_date, :termination_date, :gross_salary, :employee_401k, :employer_401k

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.xml
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.xml
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.xml
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.xml
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.valid?
        format.html { redirect_to(@employee, :notice => 'Employee was successfully created.') }
        format.xml  { render :xml => @employee, :status => :created, :location => @employee }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.xml
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to(@employee, :notice => 'Employee was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.xml
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to(employees_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_initial %><br />
    <%= f.text_field :middle_initial %>
  </div>
  <div class="field">
    <%= f.label :ssn %><br />
    <%= f.text_field :ssn %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br />
    <%= f.date_select :birth_date %>
  </div>
  <div class="field">
    <%= f.label :hire_date %><br />
    <%= f.date_select :hire_date %>
  </div>
  <div class="field">
    <%= f.label :termination_date %><br />
    <%= f.date_select :termination_date %>
  </div>
  <div class="field">
    <%= f.label :gross_salary %><br />
    <%= f.text_field :gross_salary %>
  </div>
  <div class="field">
    <%= f.label :employee_401k %><br />
    <%= f.text_field :employee_401k %>
  </div>
  <div class="field">
    <%= f.label :employer_401k %><br />
    <%= f.text_field :employer_401k %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Last name</th>
    <th>First name</th>
    <th>Middle initial</th>
    <th>Ssn</th>
    <th>Birth date</th>
    <th>Hire date</th>
    <th>Termination date</th>
    <th>Gross salary</th>
    <th>Employee 401k</th>
    <th>Employer 401k</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.last_name %></td>
    <td><%= employee.first_name %></td>
    <td><%= employee.middle_initial %></td>
    <td><%= employee.ssn %></td>
    <td><%= employee.birth_date %></td>
    <td><%= employee.hire_date %></td>
    <td><%= employee.termination_date %></td>
    <td><%= employee.gross_salary %></td>
    <td><%= employee.employee_401k %></td>
    <td><%= employee.employer_401k %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Last name:</b>
  <%= @employee.last_name %>
</p>

<p>
  <b>First name:</b>
  <%= @employee.first_name %>
</p>

<p>
  <b>Middle initial:</b>
  <%= @employee.middle_initial %>
</p>

<p>
  <b>Ssn:</b>
  <%= @employee.ssn %>
</p>

<p>
  <b>Birth date:</b>
  <%= @employee.birth_date %>
</p>

<p>
  <b>Hire date:</b>
  <%= @employee.hire_date %>
</p>

<p>
  <b>Termination date:</b>
  <%= @employee.termination_date %>
</p>

<p>
  <b>Gross salary:</b>
  <%= @employee.gross_salary %>
</p>

<p>
  <b>Employee 401k:</b>
  <%= @employee.employee_401k %>
</p>

<p>
  <b>Employer 401k:</b>
  <%= @employee.employer_401k %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Csv401k</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>